import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* // bootstrap icons */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"></link>

        {/* // Initial theme checking script */}
        <Script id="theme_init">
          {
            `(function() {
              if (typeof window !== 'undefined') {
                try {
                  let theme = localStorage.getItem("theme");
                  if(!theme && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                    theme = "dark";
                  }
                  if (theme === "dark") {
                    document.documentElement.classList.add("dark");
                  } else {
                    document.documentElement.classList.remove("dark");
                  }
                } catch (e) { console.error("Couldn't initialize theme."); }
              }
              document.body.classList.remove("hidden");
            })();`
          }
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased hidden`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
